name: CI

on:
  push:

jobs:
  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2
    with:
      args: "--all-projects args: --severity-threshold=high"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
